name: Java Maven Build
on:
    push:
        branches: ["master"]

jobs:
    build:
        name: Build-Project
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java 11 for x64
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
                architecture: x64
                cache: maven
            - name: Checkout Other Repo
              uses: actions/checkout@v4
              with:
                repository: AyushSrivastava2023/randomUsers
                token: ${{ secrets.PAT_TOKEN }}

            - name: Maven Build
              run: |
                mvn -f randomuserprofilefetcher/pom.xml clean package -DskipTests
                mvn -f randomUsers/randomuserprofilefetcher/pom.xml clean package -DskipTests
        
            - name: Store In Artifact
              uses: actions/upload-artifact@v3
              with:
                name: target
                path: |
                  /home/runner/work/RandomUsersGenerator/RandomUsersGenerator/randomuserprofilefetcher/target
                  /home/runner/work/RandomUsersGenerator/RandomUsersGenerator/randomUsers/target
        

            
            
        
            
