name: Java Maven Build
on:
    push:
        branches: ["master"]

jobs:
    build:
        name: Build-Project
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java 11 for x64
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
                architecture: x64
                cache: maven
            - name: Maven Build
              run: mvn -f randomuserprofilefetcher/pom.xml clean package -DskipTests

            
            
        
            
